package net.cworks.treefs.spi;

public enum TreePathContentType {
    APPLICATION_7Z_COMPRESSED ("application/x-7z-compressed"),
    APPLICATION_ACCESS ("application/msaccess"),
    APPLICATION_BCPIO ("application/x-bcpio"),
    APPLICATION_CPIO ("application/x-cpio"),
    APPLICATION_DVI ("application/x-dvi"),
    APPLICATION_FLASH ("application/x-shockwave-flash"),
    APPLICATION_JAR_ARCHIVE ("application/java-archive"),
    APPLICATION_JAVA ("text/x-java"),
    APPLICATION_JAVA_SERIALIZED_OBJECT ("application/java-serialized-object"),
    APPLICATION_JAVA_VM ("application/java-vm"),
    APPLICATION_JAVASCRIPT ("application/x-javascript"),
    APPLICATION_JNLP ("application/x-java-jnlp-file"),
    APPLICATION_JSON ("application/json"),
    APPLICATION_LATEXT ("application/x-latex"),
    APPLICATION_MS_DOS_PROGRAM ("application/x-msdos-program"),
    APPLICATION_MS_EXCEL ("application/vnd.ms-excel"),
    APPLICATION_MS_POWERPOINT ("application/vnd.ms-powerpoint"),
    APPLICATION_MS_VISIO ("application/vnd.visio"),
    APPLICATION_MS_WORD ("application/msword"),
    APPLICATION_OCTET_STREAM ("application/octet-stream"),
    APPLICATION_OGG ("application/ogg"),
    APPLICATION_OPENDOCUMENT_CHART ("application/vnd.oasis.opendocument.chart"),
    APPLICATION_OPENDOCUMENT_DATABASE ("application/vnd.oasis.opendocument.database"),
    APPLICATION_OPENDOCUMENT_GRAPHICS ("application/vnd.oasis.opendocument.graphics"),
    APPLICATION_OPENDOCUMENT_IMAGE ("application/vnd.oasis.opendocument.image"),
    APPLICATION_OPENDOCUMENT_PRESENTAION ("application/vnd.oasis.opendocument.presentation"),
    APPLICATION_OPENDOCUMENT_SPREADSHEET ("application/vnd.oasis.opendocument.spreadsheet"),
    APPLICATION_OPENDOCUMENT_TEXT ("application/vnd.oasis.opendocument.text"),
    APPLICATION_OPENDOCUMENT_TEXT_WEB ("application/vnd.oasis.opendocument.text-web"),
    APPLICATION_PDF ("application/pdf"),
    APPLICATION_PGP_KEYS ("application/pgp-keys"),
    APPLICATION_POSTSCRIPT ("application/postscript"),
    APPLICATION_RTF ("application/rtf"),
    APPLICATION_TAR ("application/x-tar"),
    APPLICATION_WORDPERFECT ("application/wordperfect"),
    APPLICATION_X509_CA_CERT ("application/x-x509-ca-cert"),
    APPLICATION_XHTML ("application/xhtml+xml"),
    APPLICATION_XML ("application/xml"),
    APPLICATION_ZIP ("application/zip"),
    AUDIO_MP2 ("audio/mpeg"),
    AUDIO_MP3 ("audio/mpeg"),
    AUDIO_MPEG ("audio/mpeg"),
    AUDIO_OGG ("audio/ogg"),
    AUDIO_WAV ("audio/x-wav"),
    IMAGE_GIF ("image/gif"),
    IMAGE_JPEG ("image/jpeg"),
    IMAGE_MS_BMP ("image/x-ms-bmp"),
    IMAGE_PHOTOSHOP ("image/x-photoshop"),
    IMAGE_PNG ("image/png"),
    IMAGE_SVG ("image/svg+xml"),
    IMAGE_TIFF ("image/tiff"),
    TEXT_CALENDAR ("text/calendar"),
    TEXT_CSS ("text/css"),
    TEXT_CSV ("text/csv"),
    TEXT_HTM ("text/htm"),
    TEXT_HTML ("text/html"),
    TEXT_PLAIN ("text/plain"),
    TEXT_RICHTEXT ("text/richtext"),
    VIDEO_MP4 ("video/mp4"),
    VIDEO_MSVIDEO ("video/x-msvideo"),
    VIDEO_OGG ("video/ogg"),
    VIDEO_QUICKTIME ("video/quicktime");

    public String contentType;

    TreePathContentType(String contentType) {
        this.contentType = contentType;
    }
}
